version: "3"

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto_library_bot
    environment:
      - MONGO_URL=${URL}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "8082:8081"

volumes:
  mongo-data:
